### PR TITLE
BigtableType cleaned up. Additional writer/reader settings moved out to builders.

### PR DESCRIPTION
**Pull request by stormy-ua**
Bigtable interface cleaned up and now conforms to ```Converter[T, Reader, Writer]``` interface.

In addition to ```to/from``` functions coming from ```Converter```, ```BigtableType``` exposes writer and reader builders, which could be used to append additional settings to writer/reader;

```scala
  val mutations = BigtableType[Required]
    .toBuilder
    .withColumnFamily("cf")
    .withTimestamp(123L)
    .build
    .to(Required(true, 2, "a"))

  val row = mutationsToRow(mutations)

  val copy = BigtableType[Required]
    .fromBuilder
    .withColumnFamily("cf")
    .build
    .from(row)
```

If there is no need for an additional configuration then ```BigtableType``` could used directly e.g.:

```scala
  val mutations = BigtableType[Required]
    .to(Required(true, 2, "a"))

  val row = mutationsToRow(mutations)

  val copy = BigtableType[Required]
    .from(row)
```

### CODE REVIEW

**Comment by nevillelyh** [comment]
Oops didn't realize you were already working on this. I cleaned up a bit in #85. Will comment there.

**Comment by stormy-ua** [comment]
> Oops didn't realize you were already working on this. I cleaned up a bit in #85. Will comment there.

I was trying to focus only on these enhancements:

*  decouple additional parameters (columnFamily, timestamp etc.) from Converter functions (to/from) 
* expose a familiar builder-like interface through ```BigtableType```, so a user can optionally append an additional set of parameters if needed
* split settings for reader and writer e.g. timestamp isn't being used now for reading (```from```) so it would be confusing for a user to provide it without seeing any effect. In addition, I feel like there might requests for additional reader/writer parameters to add and they might not be the same for both reader and writer.

**Comment by nevillelyh** [comment]
What about making the writer type `Seq[Mutation.Builder]` instead of `Seq[Mutation]` like other protobuf based converters like [`ExampleType`](https://github.com/spotify/magnolify/blob/master/tensorflow/src/main/scala/magnolify/tensorflow/ExampleType.scala#L31)?

That way we don't have to expose any additional parameters, since the user can just chain additional builder methods and `.build()` when reader, e.g.: `xs.map(_.setTimestampMicros(.).build()`.

**Comment by stormy-ua** [comment]
I like the idea of building `Mutation.Builder` instead of Mutation! It doesn’t solve the issue with the reader though, because we are reading from a Row and need to know familyName and other query params in advance. Maybe it might be a good idea to expose `Seq[Mutation.Builder]` directly for writer and some “query builder” for reader e.g. ```
BigtableType[T].query.withFamilyName(“f”).from(row)
```?

**Comment by nevillelyh** [comment]
Yeah in my PR I lifted `columnFamily` & `timestampMicros` to `def apply` method assuming that all rows of the same type `T` should be stored under the same column family.

OTOH we can go even further, replacing `Row` with `List[RowCell]`, moving the responsibility of column family logic to user code. In addition, since we're talking about `Seq[Mutation]` with` Seq[Mutation.Builder]`, even the `timestampMicros` logic can be move out of the converter and left to user.

By doing this we can basically decouple any storage logic from `BigtableType`, and only offer core data type conversion logic, which is more consistent with the other converters, WDYT?

**Comment by nevillelyh** [comment]
Updated #85 again. I'm now using `java.util.List[RowCell]` & `Seq[SetCell.Builder]` for reader/writer types to allow most control inside the conversion. Handling of column family & timestamp is now done at `BigtableType#apply` layer which also converts reader/writer types to `Row` & `Seq[Mutation]` for user consumption.

**Comment by stormy-ua** [comment]
> Updated #85 again. I'm now using `java.util.List[RowCell]` & `Seq[SetCell.Builder]` for reader/writer types to allow most control inside the conversion. Handling of column family & timestamp is now done at `BigtableType#apply` layer which also converts reader/writer types to `Row` & `Seq[Mutation]` for user consumption. Any additional argument can be handled there as well.

Yeah, already saw your updates and left comments there. Will be closing this PR for now. Looks like yours already has the minimum we need to be enough flexible without exposing more complex/builder API.

**Pull request closed without merging**
